### ISSUE TITLE
Notebooks with problems under kernel 22.2

### ISSUE THREAD

**Issue by forero** [desihub/tutorials#65]
The following is a summary of notebooks that show problems under kernel 22.2. The work to fix them is under progress in branch `222_compatibility`

- [x]  `FiberAssignAlgorithms_Part1.ipynb`, problem with fiberassign. A possible solution is described here: https://github.com/desihub/fiberassign/issues/429
- [x]  `FiberAssignAlgorithms_Part2.ipynb`,  problem with fiberassign. A possible solution is described here:  https://github.com/desihub/fiberassign/issues/429
- [x]  `restrict_reach.ipynb`,  problem with fiberassign. A possible solution is described here: , https://github.com/desihub/fiberassign/issues/431
- [x]  `survey-simulations.ipynb`, problem with desisurvey, https://github.com/desihub/desisurvey/issues/148
- [x]  `simulating-desi-spectra.ipynb`, problem with desisim, https://github.com/desihub/desisim/issues/567
- [x]  `Dec2020/galaxies/fitting_redshifts.ipynb`, problem with redrock, https://github.com/desihub/redrock/issues/212 
- [x]  `Dec2020/galaxies/fitting_sps.ipynb`, problem with probabgs, https://github.com/changhoonhahn/provabgs/issues/17
- [x]   `Dec2020/quickquasars/quickquasars.ipynb` problem with desispec https://github.com/desihub/desispec/issues/1796
- [x]  `Dec2020/ML_TensorFlow/ML_TensorFlow.ipynb` problem finding tensorflow and quasarnet
- [x] `redrock/RedrockOutputs.ipynb` problem reading data `ValueError: Required input 'faprogram' is not set for type 'spectra'!`

**Comment by forero** [comment]
All `Dec2020` notebooks have been restored to their original versions.

**Comment by forero** [comment]
All notebooks that handle simulated data (`survey_simulations` and `simulating-desi-spectra`) have been moved into `archive`.

**Comment by forero** [comment]
The following notebooks have been restored to kernel 20.8: FiberAssignAlgorithms_Part1.ipynb, FiberAssignAlgorithms_Part2.ipynb, restrict_reach.ipynb, redrock/RedrockOutputs.ipynb.

**Comment by weaverba137** [comment]
Does this need to be left open, since all tasks are done and #66 has been merged?

**Comment by forero** [comment]
You are right, @weaverba137. Closing it!
